components {
  id: "tiles"
  component: "/main/world/level/debug_tiles.tilemap"
}
components {
  id: "level"
  component: "/main/world/level/level.script"
}
components {
  id: "hitbox_factory"
  component: "/main/actor/hitboxes/hitbox_factory.factory"
}
embedded_components {
  id: "collision_object"
  type: "collisionobject"
  data: "collision_shape: \"/main/world/level/debug_tiles.tilemap\"\n"
  "type: COLLISION_OBJECT_TYPE_KINEMATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"world\"\n"
  "mask: \"actor\"\n"
  "mask: \"player_hitbox\"\n"
  "mask: \"enemy_hitbox\"\n"
  ""
}
embedded_components {
  id: "dummy1"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_TRIGGER\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"player_hitbox\"\n"
  "mask: \"enemy_hurtbox\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  data: 0.5\n"
  "  data: 0.5\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
embedded_components {
  id: "dummy2"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_TRIGGER\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"enemy_hitbox\"\n"
  "mask: \"player_hurtbox\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  data: 0.5\n"
  "  data: 0.5\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
